---
ignore-patterns:
  - '.yarn'
  - 'dist/'
ignores:
  # Ignore depcheck itself (seems to be required for monorepos)
  - 'depcheck'
  # Ignore tsd even if it not used yet in some packages
  - 'tsd'
  # Ignore dependencies imported implicitly by TypeScript
  - '@types/*'
  # Ignore peer dependencies that appears unused, but are required
  - 'webextension-polyfill'
  # Ignore tools (packages which we use as executables and not libraries)
  - 'rimraf'
  - '@lavamoat/allow-scripts'
  - '@metamask/auto-changelog'
  - '@metamask/create-release-branch'
  - 'ts-node'
  - 'ts-jest'
  - 'typedoc'
  # Ignore plugins implicitly imported by tools
  - 'jest-it-up'
  - 'jest-silent-reporter'
  - 'prettier-plugin-packagejson'
  # Ignore dependencies which plug into the NPM lifecycle
  - '@lavamoat/preinstall-always-fail'
  # @metamask/eth-ledger-bridge-keyring
  - '@ledgerhq/types-cryptoassets'
  - '@ledgerhq/types-devices'
  # Ignore dependency that is used with jest "directives" (thus, they cannot be detected
  # by depcheck properly)
  - 'jest-environment-jsdom'
