git tag --delete @metamask/eth-hd-keyring@@metamask/keyring-api@0.1.0
git tag --delete @metamask/eth-hd-keyring@@metamask/keyring-api@0.1.1
git tag --delete @metamask/eth-hd-keyring@@metamask/keyring-api@0.1.2
git tag --delete @metamask/eth-hd-keyring@@metamask/keyring-api@0.1.3
git tag --delete @metamask/eth-hd-keyring@@metamask/keyring-api@0.2.0
git tag --delete @metamask/eth-hd-keyring@@metamask/keyring-api@0.2.1
git tag --delete @metamask/eth-hd-keyring@@metamask/keyring-api@0.2.2
git tag --delete @metamask/eth-hd-keyring@@metamask/keyring-api@0.2.3
git tag --delete @metamask/eth-hd-keyring@@metamask/keyring-api@0.2.4
git tag --delete @metamask/eth-hd-keyring@@metamask/keyring-api@0.2.5
git tag --delete @metamask/eth-hd-keyring@@metamask/keyring-api@0.2.6
git tag --delete @metamask/eth-hd-keyring@@metamask/keyring-api@0.2.7
git tag --delete @metamask/eth-hd-keyring@@metamask/keyring-api@1.0.0
git tag --delete @metamask/eth-hd-keyring@@metamask/keyring-api@1.0.0-rc.1
git tag --delete @metamask/eth-hd-keyring@@metamask/keyring-api@1.1.0
git tag --delete @metamask/eth-hd-keyring@@metamask/keyring-api@2.0.0
git tag --delete @metamask/eth-hd-keyring@@metamask/keyring-api@3.0.0
git tag --delete @metamask/eth-hd-keyring@@metamask/keyring-api@3.1.0
git tag --delete @metamask/eth-hd-keyring@@metamask/keyring-api@3.6.0
git tag --delete @metamask/eth-hd-keyring@@metamask/keyring-api@4.0.0
git tag --delete @metamask/eth-hd-keyring@@metamask/keyring-api@4.0.1
git tag --delete @metamask/eth-hd-keyring@@metamask/keyring-api@4.0.2
git tag --delete @metamask/eth-hd-keyring@@metamask/keyring-api@5.0.0
git tag --delete @metamask/eth-hd-keyring@@metamask/keyring-api@5.0.1
git tag --delete @metamask/eth-hd-keyring@@metamask/keyring-api@5.1.0
git tag --delete @metamask/eth-hd-keyring@@metamask/keyring-api@6.0.0
git tag --delete @metamask/eth-hd-keyring@@metamask/keyring-api@6.0.1
git tag --delete @metamask/eth-hd-keyring@@metamask/keyring-api@6.0.2
git tag --delete @metamask/eth-hd-keyring@@metamask/keyring-api@6.1.0
git tag --delete @metamask/eth-hd-keyring@@metamask/keyring-api@6.1.1
git tag --delete @metamask/eth-hd-keyring@@metamask/keyring-api@6.2.0
git tag --delete @metamask/eth-hd-keyring@@metamask/keyring-api@6.2.1
git tag --delete @metamask/eth-hd-keyring@@metamask/keyring-api@6.3.0
git tag --delete @metamask/eth-hd-keyring@@metamask/keyring-api@6.3.1
git tag --delete @metamask/eth-hd-keyring@@metamask/keyring-api@6.4.0
git tag --delete @metamask/eth-hd-keyring@@metamask/keyring-api@7.0.0
git tag --delete @metamask/eth-hd-keyring@@metamask/keyring-api@7.0.1
git tag --delete @metamask/eth-hd-keyring@@metamask/keyring-api@8.0.0
git tag --delete @metamask/eth-hd-keyring@@metamask/keyring-api@8.0.1
git tag --delete @metamask/eth-hd-keyring@@metamask/keyring-api@8.0.2
git tag --delete @metamask/eth-hd-keyring@@metamask/keyring-api@8.1.0
