/* eslint-disable @typescript-eslint/naming-convention */
import {
  ErrorCode,
  Severity,
  Category,
  RetryStrategy,
} from './hardware-errors-enums';

export const HARDWARE_MAPPINGS = {
  ledger: {
    vendorName: 'Ledger',
    errorMappings: {
      '0x9000': {
        customCode: ErrorCode.Success,
        message: 'Operation successful',
        severity: Severity.Info,
        category: Category.Success,
        retryStrategy: RetryStrategy.NoRetry,
        userActionable: false,
      },
      '0x6300': {
        customCode: ErrorCode.AuthFailed,
        message: 'Authentication failed',
        severity: Severity.Err,
        category: Category.Authentication,
        retryStrategy: RetryStrategy.NoRetry,
        userActionable: true,
        userMessage: 'Authentication failed. Please verify your credentials.',
      },
      '0x63c0': {
        customCode: ErrorCode.AuthPinAttemptsRemaining,
        message: 'PIN attempts remaining',
        severity: Severity.Warning,
        category: Category.Authentication,
        retryStrategy: RetryStrategy.Retry,
        userActionable: true,
        userMessage: 'Incorrect PIN. Please try again.',
      },
      '0x6982': {
        customCode: ErrorCode.AuthSecurityCondition,
        message: 'Security conditions not satisfied',
        severity: Severity.Err,
        category: Category.Authentication,
        retryStrategy: RetryStrategy.NoRetry,
        userActionable: true,
        userMessage:
          'Device is locked or access rights are insufficient. Please unlock your device.',
      },
      '0x6985': {
        customCode: ErrorCode.UserRejected,
        message: 'User rejected action on device',
        severity: Severity.Warning,
        category: Category.UserAction,
        retryStrategy: RetryStrategy.Retry,
        userActionable: true,
        userMessage:
          'Transaction was rejected. Please approve on your device to continue.',
      },
      '0x9804': {
        customCode: ErrorCode.AuthSecurityCondition,
        message: 'App update required',
        severity: Severity.Err,
        category: Category.Authentication,
        retryStrategy: RetryStrategy.NoRetry,
        userActionable: true,
        userMessage: 'Please update your Ledger app to continue.',
      },
      '0x9808': {
        customCode: ErrorCode.AuthFailed,
        message: 'Contradiction in secret code status',
        severity: Severity.Err,
        category: Category.Authentication,
        retryStrategy: RetryStrategy.NoRetry,
        userActionable: false,
      },
      '0x9840': {
        customCode: ErrorCode.AuthDeviceBlocked,
        message: 'Code blocked',
        severity: Severity.Critical,
        category: Category.Authentication,
        retryStrategy: RetryStrategy.NoRetry,
        userActionable: true,
        userMessage:
          'Your device is blocked due to too many failed attempts. Please follow device recovery procedures.',
      },
      '0x650f': {
        customCode: ErrorCode.ConnClosed,
        message: 'App closed or connection issue',
        severity: Severity.Err,
        category: Category.Connection,
        retryStrategy: RetryStrategy.Retry,
        userActionable: true,
        userMessage:
          'Connection lost or app closed. Please open the corresponding app on your Ledger device.',
      },
      '0x5515': {
        customCode: ErrorCode.AuthDeviceLocked,
        message: 'Device is locked',
        severity: Severity.Err,
        category: Category.Authentication,
        retryStrategy: RetryStrategy.NoRetry,
        userActionable: true,
        userMessage: 'Please unlock your Ledger device to continue.',
      },
      '0x5501': {
        customCode: ErrorCode.UserRejected,
        message: 'User refused on device',
        severity: Severity.Warning,
        category: Category.UserAction,
        retryStrategy: RetryStrategy.Retry,
        userActionable: true,
        userMessage:
          'Transaction was rejected. Please approve on your device to continue.',
      },
      '0x6a80': {
        customCode: ErrorCode.DeviceStateBlindSignNotSupported,
        message: 'Blind signing not supported',
        severity: Severity.Err,
        category: Category.DeviceState,
        retryStrategy: RetryStrategy.NoRetry,
        userActionable: true,
        userMessage: 'Blind signing is not supported on this device.',
      },
      '0x6d00': {
        customCode: ErrorCode.DeviceStateOnlyV4Supported,
        message: 'Ledger Only V4 supported',
        severity: Severity.Err,
        category: Category.DeviceState,
        retryStrategy: RetryStrategy.NoRetry,
        userActionable: true,
        userMessage: 'Only V4 is supported on this device.',
      },
      '0x6e00': {
        customCode: ErrorCode.DeviceStateEthAppClosed,
        message: 'Ethereum app closed',
        severity: Severity.Err,
        category: Category.DeviceState,
        retryStrategy: RetryStrategy.NoRetry,
        userActionable: true,
        userMessage: 'Ethereum app is closed. Please open it to continue.',
      },
      '0x6501': {
        customCode: ErrorCode.DeviceStateEthAppOutOfDate,
        message: 'Ethereum app out of date',
        severity: Severity.Err,
        category: Category.DeviceState,
        retryStrategy: RetryStrategy.NoRetry,
        userActionable: true,
        userMessage:
          'Ethereum app is out of date. Please update it to continue.',
      },
    },
  },
  trezor: {
    vendorName: 'Trezor',
    errorMappings: {
      '1': {
        customCode: ErrorCode.ProtoUnexpectedMessage,
        message: 'Unexpected message received',
        severity: Severity.Err,
        category: Category.Protocol,
        retryStrategy: RetryStrategy.Retry,
        userActionable: false,
        originalName: 'Failure_UnexpectedMessage',
      },
      '2': {
        customCode: ErrorCode.UserConfirmationRequired,
        message: 'Button confirmation required',
        severity: Severity.Warning,
        category: Category.UserAction,
        retryStrategy: RetryStrategy.Retry,
        userActionable: true,
        userMessage: 'Please confirm the action on your Trezor device.',
        originalName: 'Failure_ButtonExpected',
      },
      '4': {
        customCode: ErrorCode.UserCancelled,
        message: 'Action cancelled by user',
        severity: Severity.Warning,
        category: Category.UserAction,
        retryStrategy: RetryStrategy.Retry,
        userActionable: true,
        userMessage:
          'You cancelled the operation. Please try again if this was unintentional.',
        originalName: 'Failure_ActionCancelled',
      },
      '5': {
        customCode: ErrorCode.UserInputRequired,
        message: 'PIN entry expected',
        severity: Severity.Warning,
        category: Category.UserAction,
        retryStrategy: RetryStrategy.Retry,
        userActionable: true,
        userMessage: 'Please enter your PIN on the Trezor device.',
        originalName: 'Failure_PinExpected',
      },
      '6': {
        customCode: ErrorCode.AuthPinCancelled,
        message: 'PIN cancelled by user',
        severity: Severity.Warning,
        category: Category.Authentication,
        retryStrategy: RetryStrategy.Retry,
        userActionable: true,
        userMessage: 'PIN entry was cancelled. Please try again.',
        originalName: 'Failure_PinCancelled',
      },
      '7': {
        customCode: ErrorCode.AuthIncorrectPin,
        message: 'PIN invalid',
        severity: Severity.Err,
        category: Category.Authentication,
        retryStrategy: RetryStrategy.Retry,
        userActionable: true,
        userMessage: 'Incorrect PIN entered. Please try again.',
        originalName: 'Failure_PinInvalid',
      },
      '11': {
        customCode: ErrorCode.DeviceNotReady,
        message: 'Device not initialized',
        severity: Severity.Err,
        category: Category.DeviceState,
        retryStrategy: RetryStrategy.NoRetry,
        userActionable: true,
        userMessage:
          'Your Trezor device needs to be initialized. Please set it up first.',
        originalName: 'Failure_NotInitialized',
      },
      '13': {
        customCode: ErrorCode.AuthWipeCodeMismatch,
        message: 'Wipe code mismatch',
        severity: Severity.Err,
        category: Category.Authentication,
        retryStrategy: RetryStrategy.Retry,
        userActionable: true,
        userMessage: 'Wipe codes do not match. Please try again.',
        originalName: 'Failure_WipeCodeMismatch',
      },
      '14': {
        customCode: ErrorCode.DeviceInvalidSession,
        message: 'Invalid session',
        severity: Severity.Err,
        category: Category.DeviceState,
        retryStrategy: RetryStrategy.Retry,
        userActionable: false,
        userMessage: 'Session expired. Please reconnect your device.',
        originalName: 'Failure_InvalidSession',
      },
      '15': {
        customCode: ErrorCode.DeviceCallInProgress,
        message: 'Device busy',
        severity: Severity.Warning,
        category: Category.DeviceState,
        retryStrategy: RetryStrategy.ExponentialBackoff,
        userActionable: false,
        userMessage: 'Device is busy. Please wait and try again.',
        originalName: 'Failure_Busy',
      },
      UNKNOWN: {
        customCode: ErrorCode.Unknown,
        message: 'Unknown error',
        severity: Severity.Err,
        category: Category.Unknown,
        retryStrategy: RetryStrategy.NoRetry,
        userActionable: false,
        userMessage:
          'An unknown error occurred. Please try again or contact support.',
        originalName: 'Failure_UnknownCode',
      },
      Init_IframeBlocked: {
        customCode: ErrorCode.ConnBlocked,
        message: 'Iframe blocked',
        severity: Severity.Err,
        category: Category.Connection,
        retryStrategy: RetryStrategy.NoRetry,
        userActionable: true,
        userMessage:
          'Connection blocked. Please check your browser settings and allow iframes.',
        sdkMessage: 'Iframe blocked',
      },
      Init_IframeTimeout: {
        customCode: ErrorCode.ConnTimeout,
        message: 'Iframe connection timeout',
        severity: Severity.Err,
        category: Category.Connection,
        retryStrategy: RetryStrategy.Retry,
        userActionable: false,
        userMessage:
          'Connection timed out. Please check your internet connection and try again.',
        sdkMessage: 'Iframe timeout',
      },
      Popup_ConnectionMissing: {
        customCode: ErrorCode.ConnIframeMissing,
        message: 'Unable to establish connection with iframe',
        severity: Severity.Err,
        category: Category.Connection,
        retryStrategy: RetryStrategy.Retry,
        userActionable: false,
        userMessage: 'Connection failed. Please try again.',
        sdkMessage: 'Unable to establish connection with iframe',
      },
      Desktop_ConnectionMissing: {
        customCode: ErrorCode.ConnSuiteMissing,
        message: 'Unable to establish connection with Suite',
        severity: Severity.Err,
        category: Category.Connection,
        retryStrategy: RetryStrategy.Retry,
        userActionable: true,
        userMessage:
          'Cannot connect to Trezor Suite. Please ensure Trezor Suite is running.',
        sdkMessage: 'Unable to establish connection with Suite',
      },
      Transport_Missing: {
        customCode: ErrorCode.ConnTransportMissing,
        message: 'Transport is missing',
        severity: Severity.Err,
        category: Category.Connection,
        retryStrategy: RetryStrategy.Retry,
        userActionable: true,
        userMessage:
          'Transport layer not available. Please reconnect your device.',
        sdkMessage: 'Transport is missing',
      },
      Method_Cancel: {
        customCode: ErrorCode.UserCancelled,
        message: 'Method cancelled by user',
        severity: Severity.Warning,
        category: Category.UserAction,
        retryStrategy: RetryStrategy.Retry,
        userActionable: true,
        userMessage: 'Operation was cancelled.',
        sdkMessage: 'Cancelled',
      },
      Method_Interrupted: {
        customCode: ErrorCode.UserCancelled,
        message: 'Popup closed by user',
        severity: Severity.Warning,
        category: Category.UserAction,
        retryStrategy: RetryStrategy.Retry,
        userActionable: true,
        userMessage: 'Operation interrupted. The popup was closed.',
        sdkMessage: 'Popup closed',
      },
      Method_UnknownCoin: {
        customCode: ErrorCode.Unknown,
        message: 'Coin not found',
        severity: Severity.Err,
        category: Category.Unknown,
        retryStrategy: RetryStrategy.NoRetry,
        userActionable: true,
        userMessage: 'The requested cryptocurrency is not supported.',
        sdkMessage: 'Coin not found',
      },
      Method_AddressNotMatch: {
        customCode: ErrorCode.Unknown,
        message: 'Addresses do not match',
        severity: Severity.Err,
        category: Category.Unknown,
        retryStrategy: RetryStrategy.NoRetry,
        userActionable: true,
        userMessage: 'Address verification failed. The addresses do not match.',
        sdkMessage: 'Addresses do not match',
      },
      Method_Discovery_BundleException: {
        customCode: ErrorCode.Unknown,
        message: 'Discovery bundle exception',
        severity: Severity.Err,
        category: Category.Unknown,
        retryStrategy: RetryStrategy.Retry,
        userActionable: false,
      },
      Method_Override: {
        customCode: ErrorCode.Unknown,
        message: 'Method override',
        severity: Severity.Warning,
        category: Category.Unknown,
        retryStrategy: RetryStrategy.NoRetry,
        userActionable: false,
        sdkMessage: 'override',
      },
      Device_NotFound: {
        customCode: ErrorCode.DeviceNotFound,
        message: 'Device not found',
        severity: Severity.Err,
        category: Category.DeviceState,
        retryStrategy: RetryStrategy.Retry,
        userActionable: true,
        userMessage:
          'Trezor device not detected. Please connect your device and try again.',
        sdkMessage: 'Device not found',
      },
      Device_InitializeFailed: {
        customCode: ErrorCode.DeviceNotReady,
        message: 'Device initialization failed',
        severity: Severity.Err,
        category: Category.DeviceState,
        retryStrategy: RetryStrategy.Retry,
        userActionable: true,
        userMessage:
          'Failed to initialize device. Please reconnect and try again.',
      },
      Device_ModeException: {
        customCode: ErrorCode.DeviceIncompatibleMode,
        message: 'Device mode exception',
        severity: Severity.Err,
        category: Category.DeviceState,
        retryStrategy: RetryStrategy.NoRetry,
        userActionable: true,
        userMessage:
          'Device is in an incompatible mode. Please check your device settings.',
      },
      Device_Disconnected: {
        customCode: ErrorCode.DeviceDisconnected,
        message: 'Device disconnected',
        severity: Severity.Err,
        category: Category.DeviceState,
        retryStrategy: RetryStrategy.Retry,
        userActionable: true,
        userMessage:
          'Device was disconnected. Please reconnect your Trezor device.',
        sdkMessage: 'Device disconnected',
      },
      Device_UsedElsewhere: {
        customCode: ErrorCode.DeviceUsedElsewhere,
        message: 'Device is used in another window',
        severity: Severity.Err,
        category: Category.DeviceState,
        retryStrategy: RetryStrategy.NoRetry,
        userActionable: true,
        userMessage:
          'Your Trezor is being used in another window or application. Please close other connections.',
        sdkMessage: 'Device is used in another window',
      },
      Device_InvalidState: {
        customCode: ErrorCode.AuthFailed,
        message: 'Passphrase is incorrect',
        severity: Severity.Err,
        category: Category.Authentication,
        retryStrategy: RetryStrategy.Retry,
        userActionable: true,
        userMessage: 'Incorrect passphrase. Please try again.',
        sdkMessage: 'Passphrase is incorrect',
      },
      Device_CallInProgress: {
        customCode: ErrorCode.DeviceCallInProgress,
        message: 'Device call in progress',
        severity: Severity.Warning,
        category: Category.DeviceState,
        retryStrategy: RetryStrategy.ExponentialBackoff,
        userActionable: false,
        userMessage: 'Another operation is in progress. Please wait.',
        sdkMessage: 'Device call in progress',
      },
      Device_MultipleNotSupported: {
        customCode: ErrorCode.DeviceMultipleConnected,
        message: 'Multiple devices are not supported',
        severity: Severity.Err,
        category: Category.DeviceState,
        retryStrategy: RetryStrategy.NoRetry,
        userActionable: true,
        userMessage:
          'Multiple devices detected. Please connect only one Trezor device.',
        sdkMessage: 'Multiple devices are not supported',
      },
      Device_MissingCapability: {
        customCode: ErrorCode.DeviceMissingCapability,
        message: 'Device is missing required capability',
        severity: Severity.Err,
        category: Category.DeviceState,
        retryStrategy: RetryStrategy.NoRetry,
        userActionable: true,
        userMessage:
          'Your device does not support this feature. A firmware update may be required.',
        sdkMessage: 'Device is missing capability',
      },
      Device_MissingCapabilityBtcOnly: {
        customCode: ErrorCode.DeviceBtcOnlyFirmware,
        message: 'Device is BTC-only, operation not supported',
        severity: Severity.Err,
        category: Category.DeviceState,
        retryStrategy: RetryStrategy.NoRetry,
        userActionable: true,
        userMessage:
          'This operation is not supported on Bitcoin-only firmware.',
        sdkMessage: 'Device is missing capability (BTC only)',
      },
    },
    default: {
      customCode: ErrorCode.Unknown,
      message: 'Unknown Trezor error',
      severity: Severity.Err,
      category: Category.Unknown,
      retryStrategy: RetryStrategy.NoRetry,
      userActionable: false,
      userMessage:
        'An unexpected error occurred. Please try again or contact support.',
    },
    error_patterns: [
      {
        pattern: '^Failure_.*',
        type: 'prefix',
        description: 'Device failure codes',
        defaultSeverity: Severity.Err,
      },
      {
        pattern: '^Init_.*',
        type: 'prefix',
        description: 'Initialization errors',
        defaultSeverity: Severity.Err,
      },
      {
        pattern: '^Method_.*',
        type: 'prefix',
        description: 'Method invocation errors',
        defaultSeverity: Severity.Err,
      },
      {
        pattern: '^Device_.*',
        type: 'prefix',
        description: 'Device state errors',
        defaultSeverity: Severity.Err,
      },
    ],
  },
};
