/* eslint-disable @typescript-eslint/naming-convention */
import {
  ErrorCode,
  Severity,
  Category,
  RetryStrategy,
} from './hardware-errors-enums';

export const HARDWARE_MAPPINGS = {
  ledger: {
    vendorName: 'Ledger',
    errorMappings: {
      '0x9000': {
        customCode: ErrorCode.SUCCESS_000,
        message: 'Operation successful',
        severity: Severity.INFO,
        category: Category.SUCCESS,
        retryStrategy: RetryStrategy.NO_RETRY,
        userActionable: false,
      },
      '0x6300': {
        customCode: ErrorCode.AUTH_SEC_001,
        message: 'Authentication failed',
        severity: Severity.ERROR,
        category: Category.AUTHENTICATION,
        retryStrategy: RetryStrategy.NO_RETRY,
        userActionable: true,
        userMessage: 'Authentication failed. Please verify your credentials.',
      },
      '0x63c0': {
        customCode: ErrorCode.AUTH_PIN_003,
        message: 'PIN attempts remaining',
        severity: Severity.WARNING,
        category: Category.AUTHENTICATION,
        retryStrategy: RetryStrategy.RETRY,
        userActionable: true,
        userMessage: 'Incorrect PIN. Please try again.',
      },
      '0x6700': {
        customCode: ErrorCode.DATA_FORMAT_001,
        message: 'Incorrect data length',
        severity: Severity.ERROR,
        category: Category.DATA_VALIDATION,
        retryStrategy: RetryStrategy.NO_RETRY,
        userActionable: false,
      },
      '0x6800': {
        customCode: ErrorCode.DATA_MISSING_001,
        message: 'Missing critical parameter',
        severity: Severity.ERROR,
        category: Category.DATA_VALIDATION,
        retryStrategy: RetryStrategy.NO_RETRY,
        userActionable: false,
      },
      '0x6981': {
        customCode: ErrorCode.PROTO_CMD_002,
        message: 'Command incompatible with file structure',
        severity: Severity.ERROR,
        category: Category.PROTOCOL,
        retryStrategy: RetryStrategy.NO_RETRY,
        userActionable: false,
      },
      '0x6982': {
        customCode: ErrorCode.AUTH_SEC_002,
        message: 'Security conditions not satisfied',
        severity: Severity.ERROR,
        category: Category.AUTHENTICATION,
        retryStrategy: RetryStrategy.NO_RETRY,
        userActionable: true,
        userMessage:
          'Device is locked or access rights are insufficient. Please unlock your device.',
      },
      '0x6985': {
        customCode: ErrorCode.USER_CANCEL_001,
        message: 'User rejected action on device',
        severity: Severity.WARNING,
        category: Category.USER_ACTION,
        retryStrategy: RetryStrategy.RETRY,
        userActionable: true,
        userMessage:
          'Transaction was rejected. Please approve on your device to continue.',
      },
      '0x6a80': {
        customCode: ErrorCode.DATA_FORMAT_002,
        message: 'Invalid data received',
        severity: Severity.ERROR,
        category: Category.DATA_VALIDATION,
        retryStrategy: RetryStrategy.NO_RETRY,
        userActionable: false,
      },
      '0x6a84': {
        customCode: ErrorCode.SYS_MEMORY_001,
        message: 'Not enough memory space',
        severity: Severity.ERROR,
        category: Category.SYSTEM,
        retryStrategy: RetryStrategy.NO_RETRY,
        userActionable: false,
      },
      '0x6a88': {
        customCode: ErrorCode.DATA_NOTFOUND_001,
        message: 'Referenced data not found',
        severity: Severity.ERROR,
        category: Category.DATA_VALIDATION,
        retryStrategy: RetryStrategy.NO_RETRY,
        userActionable: false,
      },
      '0x6a89': {
        customCode: ErrorCode.SYS_FILE_001,
        message: 'File already exists',
        severity: Severity.ERROR,
        category: Category.SYSTEM,
        retryStrategy: RetryStrategy.NO_RETRY,
        userActionable: false,
      },
      '0x6b00': {
        customCode: ErrorCode.DATA_FORMAT_003,
        message: 'Invalid parameter received',
        severity: Severity.ERROR,
        category: Category.DATA_VALIDATION,
        retryStrategy: RetryStrategy.NO_RETRY,
        userActionable: false,
      },
      '0x6d00': {
        customCode: ErrorCode.PROTO_CMD_001,
        message: 'Instruction not supported',
        severity: Severity.ERROR,
        category: Category.PROTOCOL,
        retryStrategy: RetryStrategy.NO_RETRY,
        userActionable: false,
      },
      '0x6d02': {
        customCode: ErrorCode.PROTO_MSG_001,
        message: 'Unknown APDU command',
        severity: Severity.ERROR,
        category: Category.PROTOCOL,
        retryStrategy: RetryStrategy.NO_RETRY,
        userActionable: false,
      },
      '0x6e00': {
        customCode: ErrorCode.PROTO_CMD_001,
        message: 'Class not supported',
        severity: Severity.ERROR,
        category: Category.PROTOCOL,
        retryStrategy: RetryStrategy.NO_RETRY,
        userActionable: false,
      },
      '0x6501': {
        customCode: ErrorCode.PROTO_CMD_001,
        message: 'Ethereum app specific error',
        severity: Severity.ERROR,
        category: Category.PROTOCOL,
        retryStrategy: RetryStrategy.NO_RETRY,
        userActionable: true,
        userMessage:
          'Please ensure the Ethereum app is open on your Ledger device.',
      },
      '0x6f00': {
        customCode: ErrorCode.SYS_INTERNAL_001,
        message: 'Internal device error',
        severity: Severity.CRITICAL,
        category: Category.SYSTEM,
        retryStrategy: RetryStrategy.NO_RETRY,
        userActionable: false,
        userMessage: 'An internal error occurred. Please report this issue.',
      },
      '0x6f42': {
        customCode: ErrorCode.SYS_LICENSE_001,
        message: 'Licensing error',
        severity: Severity.CRITICAL,
        category: Category.SYSTEM,
        retryStrategy: RetryStrategy.NO_RETRY,
        userActionable: false,
        userMessage: 'A licensing error occurred. Please contact support.',
      },
      '0x6faa': {
        customCode: ErrorCode.SYS_INTERNAL_001,
        message: 'Device halted',
        severity: Severity.CRITICAL,
        category: Category.SYSTEM,
        retryStrategy: RetryStrategy.NO_RETRY,
        userActionable: false,
        userMessage:
          'Device has halted. Please disconnect and reconnect your device.',
      },
      '0x9240': {
        customCode: ErrorCode.SYS_MEMORY_002,
        message: 'Memory problem',
        severity: Severity.ERROR,
        category: Category.SYSTEM,
        retryStrategy: RetryStrategy.RETRY,
        userActionable: false,
      },
      '0x9400': {
        customCode: ErrorCode.SYS_FILE_001,
        message: 'No elementary file selected',
        severity: Severity.ERROR,
        category: Category.SYSTEM,
        retryStrategy: RetryStrategy.NO_RETRY,
        userActionable: false,
      },
      '0x9402': {
        customCode: ErrorCode.DATA_FORMAT_003,
        message: 'Invalid offset',
        severity: Severity.ERROR,
        category: Category.DATA_VALIDATION,
        retryStrategy: RetryStrategy.NO_RETRY,
        userActionable: false,
      },
      '0x9404': {
        customCode: ErrorCode.DATA_NOTFOUND_002,
        message: 'File not found',
        severity: Severity.ERROR,
        category: Category.DATA_VALIDATION,
        retryStrategy: RetryStrategy.NO_RETRY,
        userActionable: false,
      },
      '0x9408': {
        customCode: ErrorCode.SYS_FILE_002,
        message: 'Inconsistent file',
        severity: Severity.ERROR,
        category: Category.SYSTEM,
        retryStrategy: RetryStrategy.NO_RETRY,
        userActionable: false,
      },
      '0x9484': {
        customCode: ErrorCode.CRYPTO_ALGO_001,
        message: 'Algorithm not supported',
        severity: Severity.ERROR,
        category: Category.CRYPTOGRAPHY,
        retryStrategy: RetryStrategy.NO_RETRY,
        userActionable: false,
      },
      '0x9485': {
        customCode: ErrorCode.CRYPTO_KEY_001,
        message: 'Invalid key check value',
        severity: Severity.ERROR,
        category: Category.CRYPTOGRAPHY,
        retryStrategy: RetryStrategy.NO_RETRY,
        userActionable: false,
      },
      '0x9802': {
        customCode: ErrorCode.CONFIG_INIT_001,
        message: 'Code not initialized',
        severity: Severity.ERROR,
        category: Category.CONFIGURATION,
        retryStrategy: RetryStrategy.NO_RETRY,
        userActionable: false,
      },
      '0x9804': {
        customCode: ErrorCode.AUTH_SEC_002,
        message: 'Access condition not fulfilled',
        severity: Severity.ERROR,
        category: Category.AUTHENTICATION,
        retryStrategy: RetryStrategy.NO_RETRY,
        userActionable: true,
      },
      '0x9808': {
        customCode: ErrorCode.AUTH_PIN_001,
        message: 'Contradiction in secret code status',
        severity: Severity.ERROR,
        category: Category.AUTHENTICATION,
        retryStrategy: RetryStrategy.NO_RETRY,
        userActionable: false,
      },
      '0x9810': {
        customCode: ErrorCode.SYS_INTERNAL_001,
        message: 'Contradiction invalidation',
        severity: Severity.ERROR,
        category: Category.SYSTEM,
        retryStrategy: RetryStrategy.NO_RETRY,
        userActionable: false,
      },
      '0x9840': {
        customCode: ErrorCode.AUTH_LOCK_002,
        message: 'Code blocked',
        severity: Severity.CRITICAL,
        category: Category.AUTHENTICATION,
        retryStrategy: RetryStrategy.NO_RETRY,
        userActionable: true,
        userMessage:
          'Your device is blocked due to too many failed attempts. Please follow device recovery procedures.',
      },
      '0x9850': {
        customCode: ErrorCode.SYS_INTERNAL_001,
        message: 'Maximum value reached',
        severity: Severity.ERROR,
        category: Category.SYSTEM,
        retryStrategy: RetryStrategy.NO_RETRY,
        userActionable: false,
      },
      '0x650f': {
        customCode: ErrorCode.CONN_CLOSED_001,
        message: 'App closed or connection issue',
        severity: Severity.ERROR,
        category: Category.CONNECTION,
        retryStrategy: RetryStrategy.RETRY,
        userActionable: true,
        userMessage:
          'Connection lost or app closed. Please open the corresponding app on your Ledger device.',
      },
      '0x5515': {
        customCode: ErrorCode.AUTH_LOCK_001,
        message: 'Device is locked',
        severity: Severity.ERROR,
        category: Category.AUTHENTICATION,
        retryStrategy: RetryStrategy.NO_RETRY,
        userActionable: true,
        userMessage: 'Please unlock your Ledger device to continue.',
      },
      '0x5501': {
        customCode: ErrorCode.USER_CANCEL_001,
        message: 'User refused on device',
        severity: Severity.WARNING,
        category: Category.USER_ACTION,
        retryStrategy: RetryStrategy.RETRY,
        userActionable: true,
        userMessage:
          'Transaction was rejected. Please approve on your device to continue.',
      },
    },
  },
  trezor: {
    vendorName: 'Trezor',
    errorMapping: {
      '1': {
        customCode: ErrorCode.PROTO_CMD_003,
        message: 'Unexpected message received',
        severity: Severity.ERROR,
        category: Category.PROTOCOL,
        retryStrategy: RetryStrategy.RETRY,
        userActionable: false,
        originalName: 'Failure_UnexpectedMessage',
      },
      '2': {
        customCode: ErrorCode.USER_CONFIRM_001,
        message: 'Button confirmation required',
        severity: Severity.WARNING,
        category: Category.USER_ACTION,
        retryStrategy: RetryStrategy.RETRY,
        userActionable: true,
        userMessage: 'Please confirm the action on your Trezor device.',
        originalName: 'Failure_ButtonExpected',
      },
      '3': {
        customCode: ErrorCode.DATA_FORMAT_002,
        message: 'Data error',
        severity: Severity.ERROR,
        category: Category.DATA_VALIDATION,
        retryStrategy: RetryStrategy.NO_RETRY,
        userActionable: false,
        originalName: 'Failure_DataError',
      },
      '4': {
        customCode: ErrorCode.USER_CANCEL_002,
        message: 'Action cancelled by user',
        severity: Severity.WARNING,
        category: Category.USER_ACTION,
        retryStrategy: RetryStrategy.RETRY,
        userActionable: true,
        userMessage:
          'You cancelled the operation. Please try again if this was unintentional.',
        originalName: 'Failure_ActionCancelled',
      },
      '5': {
        customCode: ErrorCode.USER_INPUT_001,
        message: 'PIN entry expected',
        severity: Severity.WARNING,
        category: Category.USER_ACTION,
        retryStrategy: RetryStrategy.RETRY,
        userActionable: true,
        userMessage: 'Please enter your PIN on the Trezor device.',
        originalName: 'Failure_PinExpected',
      },
      '6': {
        customCode: ErrorCode.AUTH_PIN_002,
        message: 'PIN cancelled by user',
        severity: Severity.WARNING,
        category: Category.AUTHENTICATION,
        retryStrategy: RetryStrategy.RETRY,
        userActionable: true,
        userMessage: 'PIN entry was cancelled. Please try again.',
        originalName: 'Failure_PinCancelled',
      },
      '7': {
        customCode: ErrorCode.AUTH_PIN_001,
        message: 'PIN invalid',
        severity: Severity.ERROR,
        category: Category.AUTHENTICATION,
        retryStrategy: RetryStrategy.RETRY,
        userActionable: true,
        userMessage: 'Incorrect PIN entered. Please try again.',
        originalName: 'Failure_PinInvalid',
      },
      '8': {
        customCode: ErrorCode.CRYPTO_SIGN_001,
        message: 'Invalid signature',
        severity: Severity.ERROR,
        category: Category.CRYPTOGRAPHY,
        retryStrategy: RetryStrategy.NO_RETRY,
        userActionable: false,
        originalName: 'Failure_InvalidSignature',
      },
      '9': {
        customCode: ErrorCode.SYS_INTERNAL_001,
        message: 'Process error',
        severity: Severity.ERROR,
        category: Category.SYSTEM,
        retryStrategy: RetryStrategy.RETRY,
        userActionable: false,
        userMessage: 'A processing error occurred. Please try again.',
        originalName: 'Failure_ProcessError',
      },
      '10': {
        customCode: ErrorCode.TX_FUNDS_001,
        message: 'Insufficient funds',
        severity: Severity.ERROR,
        category: Category.TRANSACTION,
        retryStrategy: RetryStrategy.NO_RETRY,
        userActionable: true,
        userMessage: 'Insufficient funds to complete this transaction.',
        originalName: 'Failure_NotEnoughFunds',
      },
      '11': {
        customCode: ErrorCode.DEVICE_STATE_001,
        message: 'Device not initialized',
        severity: Severity.ERROR,
        category: Category.DEVICE_STATE,
        retryStrategy: RetryStrategy.NO_RETRY,
        userActionable: true,
        userMessage:
          'Your Trezor device needs to be initialized. Please set it up first.',
        originalName: 'Failure_NotInitialized',
      },
      '12': {
        customCode: ErrorCode.AUTH_PIN_004,
        message: 'PIN mismatch',
        severity: Severity.ERROR,
        category: Category.AUTHENTICATION,
        retryStrategy: RetryStrategy.RETRY,
        userActionable: true,
        userMessage: 'PINs do not match. Please try again.',
        originalName: 'Failure_PinMismatch',
      },
      '13': {
        customCode: ErrorCode.AUTH_WIPE_001,
        message: 'Wipe code mismatch',
        severity: Severity.ERROR,
        category: Category.AUTHENTICATION,
        retryStrategy: RetryStrategy.RETRY,
        userActionable: true,
        userMessage: 'Wipe codes do not match. Please try again.',
        originalName: 'Failure_WipeCodeMismatch',
      },
      '14': {
        customCode: ErrorCode.DEVICE_STATE_002,
        message: 'Invalid session',
        severity: Severity.ERROR,
        category: Category.DEVICE_STATE,
        retryStrategy: RetryStrategy.RETRY,
        userActionable: false,
        userMessage: 'Session expired. Please reconnect your device.',
        originalName: 'Failure_InvalidSession',
      },
      '15': {
        customCode: ErrorCode.DEVICE_STATE_002,
        message: 'Device busy',
        severity: Severity.WARNING,
        category: Category.DEVICE_STATE,
        retryStrategy: RetryStrategy.EXPONENTIAL_BACKOFF,
        userActionable: false,
        userMessage: 'Device is busy. Please wait and try again.',
        originalName: 'Failure_Busy',
      },
      '99': {
        customCode: ErrorCode.SYS_FIRMWARE_002,
        message: 'Firmware installation failed',
        severity: Severity.CRITICAL,
        category: Category.SYSTEM,
        retryStrategy: RetryStrategy.NO_RETRY,
        userActionable: true,
        userMessage:
          'Firmware installation failed. Please contact Trezor support.',
        originalName: 'Failure_FirmwareError',
      },
      UNKNOWN: {
        customCode: ErrorCode.UNKNOWN_001,
        message: 'Unknown error',
        severity: Severity.ERROR,
        category: Category.UNKNOWN,
        retryStrategy: RetryStrategy.NO_RETRY,
        userActionable: false,
        userMessage:
          'An unknown error occurred. Please try again or contact support.',
        originalName: 'Failure_UnknownCode',
      },
      ENTROPY_CHECK: {
        customCode: ErrorCode.CRYPTO_ENTROPY_001,
        message: 'Entropy check failed',
        severity: Severity.ERROR,
        category: Category.CRYPTOGRAPHY,
        retryStrategy: RetryStrategy.NO_RETRY,
        userActionable: false,
        originalName: 'Failure_EntropyCheck',
      },
      Init_NotInitialized: {
        customCode: ErrorCode.CONFIG_INIT_001,
        message: 'TrezorConnect not initialized',
        severity: Severity.ERROR,
        category: Category.CONFIGURATION,
        retryStrategy: RetryStrategy.NO_RETRY,
        userActionable: false,
        sdkMessage: 'TrezorConnect not initialized',
      },
      Init_AlreadyInitialized: {
        customCode: ErrorCode.CONFIG_INIT_002,
        message: 'TrezorConnect already initialized',
        severity: Severity.WARNING,
        category: Category.CONFIGURATION,
        retryStrategy: RetryStrategy.NO_RETRY,
        userActionable: false,
        sdkMessage: 'TrezorConnect has been already initialized',
      },
      Init_IframeBlocked: {
        customCode: ErrorCode.CONN_BLOCKED_001,
        message: 'Iframe blocked',
        severity: Severity.ERROR,
        category: Category.CONNECTION,
        retryStrategy: RetryStrategy.NO_RETRY,
        userActionable: true,
        userMessage:
          'Connection blocked. Please check your browser settings and allow iframes.',
        sdkMessage: 'Iframe blocked',
      },
      Init_IframeTimeout: {
        customCode: ErrorCode.CONN_TIMEOUT_001,
        message: 'Iframe connection timeout',
        severity: Severity.ERROR,
        category: Category.CONNECTION,
        retryStrategy: RetryStrategy.RETRY,
        userActionable: false,
        userMessage:
          'Connection timed out. Please check your internet connection and try again.',
        sdkMessage: 'Iframe timeout',
      },
      Init_ManifestMissing: {
        customCode: ErrorCode.CONFIG_INIT_003,
        message: 'Manifest not set',
        severity: Severity.ERROR,
        category: Category.CONFIGURATION,
        retryStrategy: RetryStrategy.NO_RETRY,
        userActionable: false,
        sdkMessage: 'Manifest not set...',
      },
      Popup_ConnectionMissing: {
        customCode: ErrorCode.CONN_IFRAME_001,
        message: 'Unable to establish connection with iframe',
        severity: Severity.ERROR,
        category: Category.CONNECTION,
        retryStrategy: RetryStrategy.RETRY,
        userActionable: false,
        userMessage: 'Connection failed. Please try again.',
        sdkMessage: 'Unable to establish connection with iframe',
      },
      Desktop_ConnectionMissing: {
        customCode: ErrorCode.CONN_SUITE_001,
        message: 'Unable to establish connection with Suite',
        severity: Severity.ERROR,
        category: Category.CONNECTION,
        retryStrategy: RetryStrategy.RETRY,
        userActionable: true,
        userMessage:
          'Cannot connect to Trezor Suite. Please ensure Trezor Suite is running.',
        sdkMessage: 'Unable to establish connection with Suite',
      },
      Transport_Missing: {
        customCode: ErrorCode.CONN_TRANSPORT_001,
        message: 'Transport is missing',
        severity: Severity.ERROR,
        category: Category.CONNECTION,
        retryStrategy: RetryStrategy.RETRY,
        userActionable: true,
        userMessage:
          'Transport layer not available. Please reconnect your device.',
        sdkMessage: 'Transport is missing',
      },
      Method_InvalidPackage: {
        customCode: ErrorCode.CONFIG_METHOD_001,
        message: 'Invalid package for browser environment',
        severity: Severity.ERROR,
        category: Category.CONFIGURATION,
        retryStrategy: RetryStrategy.NO_RETRY,
        userActionable: false,
        sdkMessage: 'This package is not suitable to work with browser...',
      },
      Method_InvalidParameter: {
        customCode: ErrorCode.DATA_FORMAT_003,
        message: 'Invalid method parameter',
        severity: Severity.ERROR,
        category: Category.DATA_VALIDATION,
        retryStrategy: RetryStrategy.NO_RETRY,
        userActionable: false,
      },
      Method_NotAllowed: {
        customCode: ErrorCode.CONFIG_METHOD_001,
        message: 'Method not allowed for this configuration',
        severity: Severity.ERROR,
        category: Category.CONFIGURATION,
        retryStrategy: RetryStrategy.NO_RETRY,
        userActionable: false,
        sdkMessage: 'Method not allowed for this configuration',
      },
      Method_PermissionsNotGranted: {
        customCode: ErrorCode.CONFIG_PERM_001,
        message: 'Permissions not granted',
        severity: Severity.ERROR,
        category: Category.CONFIGURATION,
        retryStrategy: RetryStrategy.NO_RETRY,
        userActionable: true,
        userMessage:
          'Required permissions were not granted. Please allow access to continue.',
        sdkMessage: 'Permissions not granted',
      },
      Method_Cancel: {
        customCode: ErrorCode.USER_CANCEL_002,
        message: 'Method cancelled by user',
        severity: Severity.WARNING,
        category: Category.USER_ACTION,
        retryStrategy: RetryStrategy.RETRY,
        userActionable: true,
        userMessage: 'Operation was cancelled.',
        sdkMessage: 'Cancelled',
      },
      Method_Interrupted: {
        customCode: ErrorCode.USER_CANCEL_002,
        message: 'Popup closed by user',
        severity: Severity.WARNING,
        category: Category.USER_ACTION,
        retryStrategy: RetryStrategy.RETRY,
        userActionable: true,
        userMessage: 'Operation interrupted. The popup was closed.',
        sdkMessage: 'Popup closed',
      },
      Method_UnknownCoin: {
        customCode: ErrorCode.DATA_NOTFOUND_003,
        message: 'Coin not found',
        severity: Severity.ERROR,
        category: Category.DATA_VALIDATION,
        retryStrategy: RetryStrategy.NO_RETRY,
        userActionable: true,
        userMessage: 'The requested cryptocurrency is not supported.',
        sdkMessage: 'Coin not found',
      },
      Method_AddressNotMatch: {
        customCode: ErrorCode.DATA_VALIDATION_001,
        message: 'Addresses do not match',
        severity: Severity.ERROR,
        category: Category.DATA_VALIDATION,
        retryStrategy: RetryStrategy.NO_RETRY,
        userActionable: true,
        userMessage: 'Address verification failed. The addresses do not match.',
        sdkMessage: 'Addresses do not match',
      },
      Method_Discovery_BundleException: {
        customCode: ErrorCode.SYS_INTERNAL_001,
        message: 'Discovery bundle exception',
        severity: Severity.ERROR,
        category: Category.SYSTEM,
        retryStrategy: RetryStrategy.RETRY,
        userActionable: false,
      },
      Method_Override: {
        customCode: ErrorCode.CONFIG_METHOD_001,
        message: 'Method override',
        severity: Severity.WARNING,
        category: Category.CONFIGURATION,
        retryStrategy: RetryStrategy.NO_RETRY,
        userActionable: false,
        sdkMessage: 'override',
      },
      Method_NoResponse: {
        customCode: ErrorCode.PROTO_CMD_003,
        message: 'Call resolved without response',
        severity: Severity.ERROR,
        category: Category.PROTOCOL,
        retryStrategy: RetryStrategy.RETRY,
        userActionable: false,
        sdkMessage: 'Call resolved without response',
      },
      Device_NotFound: {
        customCode: ErrorCode.DEVICE_DETECT_001,
        message: 'Device not found',
        severity: Severity.ERROR,
        category: Category.DEVICE_STATE,
        retryStrategy: RetryStrategy.RETRY,
        userActionable: true,
        userMessage:
          'Trezor device not detected. Please connect your device and try again.',
        sdkMessage: 'Device not found',
      },
      Device_InitializeFailed: {
        customCode: ErrorCode.DEVICE_STATE_001,
        message: 'Device initialization failed',
        severity: Severity.ERROR,
        category: Category.DEVICE_STATE,
        retryStrategy: RetryStrategy.RETRY,
        userActionable: true,
        userMessage:
          'Failed to initialize device. Please reconnect and try again.',
      },
      Device_FwException: {
        customCode: ErrorCode.SYS_FIRMWARE_001,
        message: 'Firmware exception',
        severity: Severity.ERROR,
        category: Category.SYSTEM,
        retryStrategy: RetryStrategy.NO_RETRY,
        userActionable: true,
        userMessage:
          'Firmware error detected. Please update your device firmware.',
      },
      Device_ModeException: {
        customCode: ErrorCode.DEVICE_MODE_001,
        message: 'Device mode exception',
        severity: Severity.ERROR,
        category: Category.DEVICE_STATE,
        retryStrategy: RetryStrategy.NO_RETRY,
        userActionable: true,
        userMessage:
          'Device is in an incompatible mode. Please check your device settings.',
      },
      Device_Disconnected: {
        customCode: ErrorCode.DEVICE_STATE_003,
        message: 'Device disconnected',
        severity: Severity.ERROR,
        category: Category.DEVICE_STATE,
        retryStrategy: RetryStrategy.RETRY,
        userActionable: true,
        userMessage:
          'Device was disconnected. Please reconnect your Trezor device.',
        sdkMessage: 'Device disconnected',
      },
      Device_UsedElsewhere: {
        customCode: ErrorCode.DEVICE_STATE_004,
        message: 'Device is used in another window',
        severity: Severity.ERROR,
        category: Category.DEVICE_STATE,
        retryStrategy: RetryStrategy.NO_RETRY,
        userActionable: true,
        userMessage:
          'Your Trezor is being used in another window or application. Please close other connections.',
        sdkMessage: 'Device is used in another window',
      },
      Device_InvalidState: {
        customCode: ErrorCode.AUTH_SEC_001,
        message: 'Passphrase is incorrect',
        severity: Severity.ERROR,
        category: Category.AUTHENTICATION,
        retryStrategy: RetryStrategy.RETRY,
        userActionable: true,
        userMessage: 'Incorrect passphrase. Please try again.',
        sdkMessage: 'Passphrase is incorrect',
      },
      Device_CallInProgress: {
        customCode: ErrorCode.DEVICE_STATE_005,
        message: 'Device call in progress',
        severity: Severity.WARNING,
        category: Category.DEVICE_STATE,
        retryStrategy: RetryStrategy.EXPONENTIAL_BACKOFF,
        userActionable: false,
        userMessage: 'Another operation is in progress. Please wait.',
        sdkMessage: 'Device call in progress',
      },
      Device_MultipleNotSupported: {
        customCode: ErrorCode.DEVICE_CAP_001,
        message: 'Multiple devices are not supported',
        severity: Severity.ERROR,
        category: Category.DEVICE_STATE,
        retryStrategy: RetryStrategy.NO_RETRY,
        userActionable: true,
        userMessage:
          'Multiple devices detected. Please connect only one Trezor device.',
        sdkMessage: 'Multiple devices are not supported',
      },
      Device_MissingCapability: {
        customCode: ErrorCode.DEVICE_CAP_001,
        message: 'Device is missing required capability',
        severity: Severity.ERROR,
        category: Category.DEVICE_STATE,
        retryStrategy: RetryStrategy.NO_RETRY,
        userActionable: true,
        userMessage:
          'Your device does not support this feature. A firmware update may be required.',
        sdkMessage: 'Device is missing capability',
      },
      Device_MissingCapabilityBtcOnly: {
        customCode: ErrorCode.DEVICE_CAP_002,
        message: 'Device is BTC-only, operation not supported',
        severity: Severity.ERROR,
        category: Category.DEVICE_STATE,
        retryStrategy: RetryStrategy.NO_RETRY,
        userActionable: true,
        userMessage:
          'This operation is not supported on Bitcoin-only firmware.',
        sdkMessage: 'Device is missing capability (BTC only)',
      },
    },
    default: {
      custom_code: ErrorCode.UNKNOWN_001,
      message: 'Unknown Trezor error',
      severity: Severity.ERROR,
      category: Category.UNKNOWN,
      retry_strategy: RetryStrategy.NO_RETRY,
      userActionable: false,
      userMessage:
        'An unexpected error occurred. Please try again or contact support.',
    },
    error_patterns: [
      {
        pattern: '^Failure_.*',
        type: 'prefix',
        description: 'Device failure codes',
        defaultSeverity: Severity.ERROR,
      },
      {
        pattern: '^Init_.*',
        type: 'prefix',
        description: 'Initialization errors',
        defaultSeverity: Severity.ERROR,
      },
      {
        pattern: '^Method_.*',
        type: 'prefix',
        description: 'Method invocation errors',
        defaultSeverity: Severity.ERROR,
      },
      {
        pattern: '^Device_.*',
        type: 'prefix',
        description: 'Device state errors',
        defaultSeverity: Severity.ERROR,
      },
    ],
  },
};
