export {
  EmulatorType,
  type HardwareWalletEmulator,
  type DeviceInteraction,
} from './types';

export { createEmulator } from './factory';

export {
  Speculos,
  type SpeculosOptions,
  SpeculosClient,
  type SpeculosClientOptions,
  type APDUResponse,
  ApduBridge,
  createDeviceInteraction,
  NanoInteraction,
  TouchInteraction,
  type DeviceInteraction as LedgerDeviceInteraction,
  createProcessManager,
  type ProcessManager,
  type ProcessManagerOptions,
  type ProcessManagerStatus,
  DockerManager,
  type DockerManagerOptions,
  type DockerManagerStatus,
  getWebHidMockScript,
  DEVICE_MODELS,
  DEFAULT_DEVICE_MODEL,
  DEFAULT_DEVICE,
  DEVICE_PRESETS,
  SPECULOS_APDU_PORT,
  SPECULOS_API_PORT,
  SPECULOS_WS_BRIDGE_PORT,
  SPECULOS_LEDGER_ADDRESSES,
  SPECULOS_LEDGER_ADDRESS,
  SPECULOS_SEED,
  getDeviceModel,
  detectRunMode,
  type DeviceModel,
  type DeviceConfig,
  type InteractionType,
  type RunMode,
  withRetry,
  ExponentialBackoff,
  isRetryableError,
  createLedgerHidFramingSession,
  pushLedgerHidFrame,
  encodeLedgerHidResponse,
  type LedgerHidFramingSession,
} from './ledger';
