export {
  EmulatorType,
  type HardwareWalletEmulator,
  type DeviceInteraction,
} from './types';

export { createEmulator } from './factory';

export {
  Speculos,
  type SpeculosOptions,
  SpeculosClient,
  type SpeculosClientOptions,
  type APDUResponse,
  ApduBridge,
  createDeviceInteraction,
  NanoInteraction,
  TouchInteraction,
  type DeviceInteraction as LedgerDeviceInteraction,
  createProcessManager,
  type ProcessManager,
  type ProcessManagerOptions,
  type ProcessManagerStatus,
  DockerManager,
  type DockerManagerOptions,
  type DockerManagerStatus,
  getWebHidMockScript,
  DEVICE_MODELS,
  DEFAULT_DEVICE_MODEL,
  DEFAULT_DEVICE,
  DEVICE_PRESETS,
  SPECULOS_APDU_PORT,
  SPECULOS_API_PORT,
  SPECULOS_WS_BRIDGE_PORT,
  SPECULOS_LEDGER_ADDRESSES,
  SPECULOS_LEDGER_ADDRESS,
  SPECULOS_SEED,
  getDeviceModel,
  detectRunMode,
  type DeviceModel,
  type DeviceConfig,
  type InteractionType,
  type RunMode,
  withRetry,
  ExponentialBackoff,
  isRetryableError,
  createLedgerHidFramingSession,
  pushLedgerHidFrame,
  encodeLedgerHidResponse,
  type LedgerHidFramingSession,
} from './ledger';

export {
  SpeculosBleRunner,
  type SpeculosBleConfig,
  type SpeculosBleRunnerOptions,
} from './ble';

export {
  QrEmulator,
  type QrEmulatorOptions,
  type QrKeyringBridge,
  type QrScanRequest,
  type QrSignatureRequest,
  QrScanRequestType,
  type QrPairMode,
  type SerializedUR,
  synthesizeAccountUR,
  buildCryptoAccountUR,
  buildCryptoHDKeyUR,
  deriveAccountAddress,
  deriveKey,
  signRequest,
  decodeSignRequest,
  derivePrivateKey,
  parseXfp,
  pathToComponents,
  createKeypath,
  createCryptoHDKey,
  createCryptoOutput,
  createCryptoAccount,
  encodeToFragments,
  createEncoder,
  FragmentDecoder,
  decodeFragments,
  renderQrPng,
  renderUrToY4m,
  ensureFfmpegAvailable,
  isFfmpegAvailable,
  FfmpegUnavailableError,
  decodeQrImage,
  decodeQrScreenshots,
  QR_EMULATOR_SEED,
  QR_EMULATOR_ROOT_DERIVATION_PATH,
  QR_EMULATOR_ACCOUNT_PATH,
  QR_EMULATOR_CHILDREN_PATH,
  QR_EMULATOR_ACCOUNT_DERIVATION_PATH,
  QR_EMULATOR_DEFAULT_XFP,
  QR_EMULATOR_ADDRESS,
  QR_FRAGMENT_SIZE,
  QR_REFRESH_MS,
  QR_CODE_SIZE_PX,
  QR_UPPERCASE,
} from './qr';

export {
  TrezorEmulator,
  type TrezorEmulatorOptions,
  TrezorControllerClient,
  type ControllerClientOptions,
  type SetupParams,
  createSidecarManager,
  type TrezorSidecarManager,
  type SidecarManagerOptions,
  getTrezorConnectSrcInjectionScript,
  TrezorDockerManager,
  TrezorDeviceInteraction,
  type DeviceInteraction as TrezorDeviceInteractionType,
  MODEL_PROFILES,
  type TrezorModel,
  type ModelProfile,
  TREZOR_EMULATOR_SEED,
  TREZOR_DEFAULT_MODEL,
  TREZOR_CONNECT_SRC,
  TREZOR_TRANSPORT_BRIDGE_PORT,
  TREZOR_CONTROLLER_PORT,
  TREZOR_EMULATOR_PORT,
  TREZOR_MSG,
} from './trezor';
